2021-06-15T20:53:00.6502454-06:00;VSTestExecutionThread;Info;SpecFlow+Runner execution started
2021-06-15T20:53:00.6502454-06:00;VSTestExecutionThread;Info;SpecFlow+Runner 3.4.19 in Framework clr40 in x86 mode execution started
2021-06-15T20:53:00.6502454-06:00;VSTestExecutionThread;Info;TestAdapter Location: C:\Users\user\source\repos\PracticingSix\packages\SpecRun.Runner.3.4.19\tools\net461\TechTalk.SpecRun.VisualStudio.TestAdapter.dll
2021-06-15T20:53:00.6512454-06:00;VSTestExecutionThread;Info;Current UserName: 'user', MachineName: 'DESKTOP-5BKHEHG'
2021-06-15T20:53:00.9153046-06:00;VSTestExecutionThread;Info;SpecRun: running tests in C:\Users\user\source\repos\PracticingSix\bin\Debug\PracticingSix.dll
2021-06-15T20:53:00.9163076-06:00;VSTestExecutionThread;Info;Output folder configured to "C:\Users\user\source\repos\PracticingSix\TestResults" (default)
2021-06-15T20:53:00.9163076-06:00;VSTestExecutionThread;Info;Profile: PracticingSix
2021-06-15T20:53:00.9953221-06:00;VSTestExecutionThread;Info;Log file path: C:\Users\user\source\repos\PracticingSix\TestResults\PracticingSix_PracticingSix_2021-06-15T205300.log
2021-06-15T20:53:01.0043253-06:00;Thread#14;Info;Checking activation
2021-06-15T20:53:01.1303546-06:00;Thread#14;Info;Activated.
2021-06-15T20:53:01.1313558-06:00;Thread#14;Info;Activation check completed
2021-06-15T20:53:01.1313558-06:00;Thread#14;Info;Starting test run
2021-06-15T20:53:01.2003687-06:00;Thread#14;Info;Discovering target: Default
2021-06-15T20:53:01.2003687-06:00;Thread#14;Info;Discovering tests from assembly: C:\Users\user\source\repos\PracticingSix\bin\Debug\PracticingSix.dll
2021-06-15T20:53:01.8155958-06:00;Thread#14;Info;Discovered tests from assembly: C:\Users\user\source\repos\PracticingSix\bin\Debug\PracticingSix.dll
2021-06-15T20:53:01.8185980-06:00:Test Suite Dump
2021-06-15T20:53:01.8251068-06:00:#0: PracticingSix/PracticingSix - 
2021-06-15T20:53:01.8251068-06:00:#1: Default - 
2021-06-15T20:53:01.8251068-06:00:#2: PracticingSix - 
2021-06-15T20:53:01.8251068-06:00:#3: EyeOfTheTiger - 
2021-06-15T20:53:01.8791184-06:00:#4: Hit Me and Don't Stop - TestAssembly:PracticingSix/Feature:EyeOfTheTiger/Scenario:Hit+Me+and+Don%27t+Stop
2021-06-15T20:53:01.8791184-06:00:End: Test Suite Dump
2021-06-15T20:53:01.9356624-06:00:Thread#1:Scheduler: get next test for thread 1
2021-06-15T20:53:01.9396641-06:00:Thread#:Scheduler: testitem #4 from normal test queue 
2021-06-15T20:53:01.9396641-06:00:Thread#1:Scheduler: considering testitem #4 for thread 1
2021-06-15T20:53:01.9476842-06:00:Thread#1:TestItem#4:testItemMatchesCurrentTestThread:UnSpecific
2021-06-15T20:53:01.9476842-06:00:Thread#1:TestItem#4:runsOnOneOtherThreadSpecific:False
2021-06-15T20:53:01.9476842-06:00:Thread#1:TestItem#4:runsOnOneOtherThreadUnspecific:True
2021-06-15T20:53:01.9476842-06:00:Thread#1:Scheduler: using testitem #4 for thread 1
2021-06-15T20:53:01.9496841-06:00:Thread#1:Scheduler: Test #4 is scheduled for thread
2021-06-15T20:53:01.9506843-06:00:Thread#1:Scheduler: with testItemExecutionIndex 0
2021-06-15T20:53:01.9521941-06:00:Thread#0:Scheduler: get next test for thread 0
2021-06-15T20:53:01.9521941-06:00:Thread#:Scheduler: at the end of normal test queue
2021-06-15T20:53:01.9521941-06:00:Thread#0:Scheduler: enumerator for thread is at end
2021-06-15T20:53:01.9521941-06:00:Thread#0:Scheduler: No more tests for thread
2021-06-15T20:53:01.9561951-06:00:Thread #1: creating new test thread executor for PracticingSix, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (target: Default)
2021-06-15T20:53:01.9591961-06:00:Thread #1: Creating test assembly executor for execution model OutProc
2021-06-15T20:53:01.9621971-06:00:Thread #1: Creating test assembly executor for execution model OutProc
2021-06-15T20:53:01.9662269-06:00:Thread #1: using TechTalk.SpecRun.Framework.Execution.OutOfProc.StreamJsonRPC.OutOfProcessTestAssemblyExecutorHost to execute tests
2021-06-15T20:53:01.9722287-06:00:starting Out Of Process Executor
2021-06-15T20:53:01.9777458-06:00:Starting callback TCP Rpc server
2021-06-15T20:53:01.9977421-06:00:Asynchronously starting background TCP Rpc Server on port 32770
2021-06-15T20:53:01.9977421-06:00:Started callback TCP Rpc server on port 32770
2021-06-15T20:53:01.9977421-06:00:Starting logger TCP Rpc server
2021-06-15T20:53:02.0017530-06:00:Asynchronously starting background TCP Rpc Server on port 32771
2021-06-15T20:53:02.0017530-06:00:Started logger TCP Rpc server on port 32771
2021-06-15T20:53:02.0122549-06:00:Executing test executor at 'C:\Users\user\source\repos\PracticingSix\packages\SpecRun.Runner.3.4.19\tools\net461\TechTalk.SpecRun.Framework.Executor.x86.clr40.exe' '--remoteRunnerPid 31012 --uniqueId "2021-06-15T205300" --outputFolder "C:\Users\user\source\repos\PracticingSix\TestResults" --callbackPort 32770 --loggerPort 32771' in 'C:\Users\user\source\repos\PracticingSix\packages\SpecRun.Runner.3.4.19\tools\net461'
2021-06-15T20:53:02.0177736-06:00:Executor with PID 30380 has been started successfully.
2021-06-15T20:53:02.0217661-06:00:Out of Process Executor 30380 started
2021-06-15T20:53:02.0217661-06:00:Waiting for endpoint
2021-06-15T20:53:02.9131562-06:00:Remote executor port received: 32773
2021-06-15T20:53:02.9141567-06:00:Creating executor TCP client on port 32773
2021-06-15T20:53:02.9141567-06:00:Created executor TCP client on port 32773
2021-06-15T20:53:02.9141567-06:00:Connecting to remote executor TCP server
2021-06-15T20:53:02.9151558-06:00:Connected remote executor TCP server
2021-06-15T20:53:02.9151558-06:00:trying to connect to Out of Process Executor the 1 attempt
2021-06-15T20:53:02.9151558-06:00:Connection to Out of Process Executor established in the 1 attempt
2021-06-15T20:53:03.8693703-06:00:2021-06-15T20:53:03.8673691-06:00:OutOfProcessTestAssemblyExecutor: initialized for C:\Users\user\source\repos\PracticingSix\bin\Debug\PracticingSix.dll on test thread #1
2021-06-15T20:53:03.8773714-06:00:Endpoint 30380 started
2021-06-15T20:53:03.9013782-06:00:2021-06-15T20:53:03.9013782-06:00:OutOfProcessTestAssemblyExecutor: running tests...
2021-06-15T20:53:04.3984361-06:00:2021-06-15T20:53:04.3984361-06:00:Thread#1:T:-> Loading plugin C:\Users\user\source\repos\PracticingSix\bin\Debug\SpecRun.Runtime.SpecFlowPlugin.dll
2021-06-15T20:53:04.4514880-06:00:2021-06-15T20:53:04.4504885-06:00:Thread#1:T:-> Using default config
2021-06-15T20:53:05.9619417-06:00:2021-06-15T20:53:05.9619417-06:00:Thread#1:T:Starting the driver...
2021-06-15T20:53:08.4366189-06:00:Thread#1: Test #4/0 is started on thread #1
2021-06-15T20:53:08.4831397-06:00:2021-06-15T20:53:08.4811393-06:00:Thread#1:B:When I need Eye of the Tiger every 4.05 minutes
2021-06-15T20:53:25.9854597-06:00:2021-06-15T20:53:25.9834592-06:00:Thread#1:T:Playing!
2021-06-15T20:53:26.9857921-06:00:2021-06-15T20:53:26.9827899-06:00:Thread#1:T:Loop: 0
2021-06-15T20:53:32.7362287-06:00:2021-06-15T20:53:32.6942016-06:00:Thread#1:T:Switched to Confirm Permissions window
2021-06-15T20:53:35.9228407-06:00:2021-06-15T20:53:35.9228407-06:00:Thread#1:T:Finished logging in
2021-06-15T21:03:23.4696282-06:00:2021-06-15T21:03:23.4686329-06:00:Thread#1:T:Playing!
2021-06-15T21:07:37.8163876-06:00:2021-06-15T21:07:37.8153875-06:00:Thread#1:T:Playing!
2021-06-15T21:11:53.0482358-06:00:2021-06-15T21:11:53.0482358-06:00:Thread#1:T:Playing!
2021-06-15T21:15:59.7047207-06:00:2021-06-15T21:15:59.7037217-06:00:Thread#1:T:Playing!
2021-06-15T21:20:05.9673669-06:00:2021-06-15T21:20:05.9663697-06:00:Thread#1:T:Playing!
2021-06-15T21:24:12.4160899-06:00:2021-06-15T21:24:12.4160899-06:00:Thread#1:T:Playing!
2021-06-15T21:28:18.8894571-06:00:2021-06-15T21:28:18.8894571-06:00:Thread#1:T:Playing!
2021-06-15T21:32:25.2325830-06:00:2021-06-15T21:32:25.2315808-06:00:Thread#1:T:Playing!
2021-06-15T21:36:31.5662978-06:00:2021-06-15T21:36:31.5652975-06:00:Thread#1:T:Playing!
2021-06-15T21:40:38.0408603-06:00:2021-06-15T21:40:38.0398604-06:00:Thread#1:T:Playing!
2021-06-15T21:44:44.3061784-06:00:2021-06-15T21:44:44.3061784-06:00:Thread#1:T:Playing!
2021-06-15T21:48:50.8995975-06:00:2021-06-15T21:48:50.8985980-06:00:Thread#1:T:Playing!
2021-06-15T21:52:57.3620203-06:00:2021-06-15T21:52:57.3610201-06:00:Thread#1:T:Playing!
2021-06-15T21:57:03.5438806-06:00:2021-06-15T21:57:03.5428817-06:00:Thread#1:T:Playing!
2021-06-15T22:01:10.2576112-06:00:2021-06-15T22:01:10.2566103-06:00:Thread#1:T:Playing!
2021-06-15T22:05:16.5833339-06:00:2021-06-15T22:05:16.5823310-06:00:Thread#1:T:Playing!
2021-06-15T22:09:24.6476261-06:00:2021-06-15T22:09:24.6436252-06:00:Thread#1:T:Playing!
2021-06-15T22:13:36.5971117-06:00:2021-06-15T22:13:36.5961108-06:00:Thread#1:T:Playing!
2021-06-15T22:26:30.4984144-06:00:2021-06-15T22:26:30.4974134-06:00:Thread#1:T:Playing!
2021-06-15T22:30:36.9502365-06:00:2021-06-15T22:30:36.9492354-06:00:Thread#1:T:Playing!
2021-06-15T22:34:42.9080527-06:00:2021-06-15T22:34:42.9070504-06:00:Thread#1:T:Playing!
2021-06-15T22:38:49.3416352-06:00:2021-06-15T22:38:49.3396353-06:00:Thread#1:T:Playing!
2021-06-15T22:42:55.3696357-06:00:2021-06-15T22:42:55.3696357-06:00:Thread#1:T:Playing!
2021-06-15T22:47:01.6153082-06:00:2021-06-15T22:47:01.6153082-06:00:Thread#1:T:Playing!
2021-06-15T22:51:07.9254290-06:00:2021-06-15T22:51:07.9244279-06:00:Thread#1:T:Playing!
2021-06-15T22:55:14.2802254-06:00:2021-06-15T22:55:14.2792267-06:00:Thread#1:T:Playing!
2021-06-15T22:59:20.4193667-06:00:2021-06-15T22:59:20.4183660-06:00:Thread#1:T:Playing!
2021-06-15T23:03:10.0016485-06:00:RPC Server disconnected, because 'StreamError'. 
LastMessage: 
Description:Reading JSON RPC from the stream failed with IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
Exception:System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.ReadBufferingStream.<FillBufferAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.HeaderDelimitedMessageHandler.<ReadCoreAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.DelimitedMessageHandler.<ReadAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.JsonRpc.<ReadAndHandleRequestsAsync>d__97.MoveNext()
2021-06-15T23:03:10.0036481-06:00:RPC Server disconnected, because 'StreamError'. 
LastMessage: 
Description:Reading JSON RPC from the stream failed with IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
Exception:System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.ReadBufferingStream.<FillBufferAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.HeaderDelimitedMessageHandler.<ReadCoreAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.DelimitedMessageHandler.<ReadAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.JsonRpc.<ReadAndHandleRequestsAsync>d__97.MoveNext()
2021-06-15T23:03:10.0056488-06:00:RPC Client disconnected, because 'StreamError'. 
LastMessage: 
Description:Reading JSON RPC from the stream failed with IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
Exception:System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.ReadBufferingStream.<FillBufferAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.HeaderDelimitedMessageHandler.<ReadCoreAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.DelimitedMessageHandler.<ReadAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.JsonRpc.<ReadAndHandleRequestsAsync>d__97.MoveNext()
2021-06-15T23:03:10.0096500-06:00:test thread #1 error: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__88`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TechTalk.SpecFlow.Plus.RPC.TcpRpcClient.<Invoke>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TechTalk.SpecFlow.Plus.RPC.AsyncHelper.RunSync[TResult](Func`1 func)
   at TechTalk.SpecRun.Framework.Execution.OutOfProc.StreamJsonRPC.OutOfProcessTestAssemblyExecutorClient.RunTests(TestThreadState testThreadState)
   at TechTalk.SpecRun.Framework.Execution.OutOfProc.StreamJsonRPC.OutOfProcessTestAssemblyExecutorHost.RunTests(TestThreadState testThreadState)
   at TechTalk.SpecRun.Framework.TestThread.RunNonEmptyTestSuite(CancellationToken cancellationToken, TestThreadState testThreadState)
   at TechTalk.SpecRun.Framework.TestThread.Run(ITestExecutionManager executionManagerForRun, CancellationToken cancellationToken)
   at TechTalk.SpecRun.Framework.AsyncTestThreadRunner.RunSync(TestExecutionManager executionManager, CancellationToken cancellationToken)
2021-06-15T23:03:10.0106499-06:00:test thread error: TechTalk.SpecRun.Framework.SpecRunException: At least one test thread aborted. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__88`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TechTalk.SpecFlow.Plus.RPC.TcpRpcClient.<Invoke>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TechTalk.SpecFlow.Plus.RPC.AsyncHelper.RunSync[TResult](Func`1 func)
   at TechTalk.SpecRun.Framework.Execution.OutOfProc.StreamJsonRPC.OutOfProcessTestAssemblyExecutorClient.RunTests(TestThreadState testThreadState)
   at TechTalk.SpecRun.Framework.Execution.OutOfProc.StreamJsonRPC.OutOfProcessTestAssemblyExecutorHost.RunTests(TestThreadState testThreadState)
   at TechTalk.SpecRun.Framework.TestThread.RunNonEmptyTestSuite(CancellationToken cancellationToken, TestThreadState testThreadState)
   at TechTalk.SpecRun.Framework.TestThread.Run(ITestExecutionManager executionManagerForRun, CancellationToken cancellationToken)
   at TechTalk.SpecRun.Framework.AsyncTestThreadRunner.RunSync(TestExecutionManager executionManager, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
2021-06-15T23:03:10.0106499-06:00:Trying to cancel thread
2021-06-15T23:03:10.0106499-06:00:Thread cancelled
2021-06-15T23:03:10.0106499-06:00:Trying to cancel thread
2021-06-15T23:03:10.0106499-06:00:Thread cancelled
2021-06-15T23:03:10.0186514-06:00:Thread#-1:Scheduler: get next test for thread -1
2021-06-15T23:03:10.0186514-06:00:Thread#:Scheduler: at the end of normal test queue
2021-06-15T23:03:10.0186514-06:00:Thread#-1:Scheduler: enumerator for thread is at end
2021-06-15T23:03:10.0226526-06:00;Thread#14;Info;test run finished
2021-06-15T23:03:10.0226526-06:00;Thread#14;Info;publishing test results
2021-06-15T23:03:10.1497059-06:00;Thread#14;Info;test results published
2021-06-15T23:03:10.1497059-06:00;Thread#14;Info;generating reports
2021-06-15T23:03:10.3257453-06:00;Thread#14;Info;Starting external report generation process
2021-06-15T23:03:10.5537978-06:00;Thread#14;Error;Could not generate test run result reports. An error occurred in the generator.
2021-06-15T23:03:10.5537978-06:00;Thread#14;Error;External program returned exit code '-1073741502'
2021-06-15T23:03:10.5547960-06:00;Thread#14;Info;Failed generating reports
2021-06-15T23:03:10.5697997-06:00:Total: 1 (test executions: 0)
2021-06-15T23:03:10.5728006-06:00:Succeeded: 0
2021-06-15T23:03:10.5728006-06:00:Ignored: 0
2021-06-15T23:03:10.5738007-06:00:Pending: 0
2021-06-15T23:03:10.5738007-06:00:Skipped: 0
2021-06-15T23:03:10.5738007-06:00:Failed: 0
2021-06-15T23:03:10.5778014-06:00;VSTestExecutionThread;Info;Adding attachments to VSTest
========== End of log file ==========
